version: '2'

services:
  postgres:
    image: postgres:$PG_TAG
    ports:
      - "$DB_PORT:5432"
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    command: -c logging_collector=on -c log_destination=stderr -c log_directory=/logs -c wal_level=logical
    volumes:
      - "./pg_data/:/var/lib/postgresql/data/"
      - "./pg_logs/:/logs"
      - "./init:/docker-entrypoint-initdb.d"

